// <auto-generated />
using System;
using FiapEsperancaSolidaria.Campanha.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FiapEsperancaSolidaria.Campanha.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("fundraising")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FiapEsperancaSolidaria.Campanha.Domain.Aggregates.CampaignAggregate.Campaign", b =>
                {
                    b.Property<Guid>("CampaignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FinancialGoal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NormalizedTitle")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasComputedColumnSql("lower(\"Title\")", true);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("TotalRaised")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CampaignId");

                    b.HasIndex("NormalizedTitle")
                        .IsUnique()
                        .HasDatabaseName("IX_Campaigns_NormalizedTitle");

                    b.HasIndex("Status");

                    b.ToTable("Campaigns", "fundraising");
                });

            modelBuilder.Entity("FiapEsperancaSolidaria.Campanha.Domain.Aggregates.CampaignAggregate.Donation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("DonationId");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("DonationStatus")
                        .HasColumnType("smallint");

                    b.Property<Guid>("DonorId")
                        .HasColumnType("uuid");

                    b.Property<byte>("PaymentMethod")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("Donation", "fundraising");
                });

            modelBuilder.Entity("FiapEsperancaSolidaria.Campanha.Domain.Aggregates.CampaignAggregate.Donation", b =>
                {
                    b.HasOne("FiapEsperancaSolidaria.Campanha.Domain.Aggregates.CampaignAggregate.Campaign", null)
                        .WithMany("Donations")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FiapEsperancaSolidaria.Campanha.Domain.Aggregates.CampaignAggregate.Campaign", b =>
                {
                    b.Navigation("Donations");
                });
#pragma warning restore 612, 618
        }
    }
}
